apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: hermes
  labels:
    app: core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: core-service
        image: ghcr.io/duosis-developer-team/hermes-core-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        # Database
        - name: CORE_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: hermes-config
              key: DB_HOST_CORE
        - name: CORE_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: hermes-config
              key: DB_PORT
        - name: CORE_DB_USER
          valueFrom:
            configMapKeyRef:
              name: hermes-config
              key: POSTGRES_USER
        - name: CORE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hermes-secrets
              key: POSTGRES_PASSWORD
        - name: CORE_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: hermes-config
              key: POSTGRES_DB_CORE
        
        # Services & Security
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: hermes-config
              key: AUTH_SERVICE_URL
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: hermes-secrets
              key: JWT_SECRET_KEY
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: hermes-jwt-auth
              key: JWT_PUBLIC_KEY
        - name: CORS_ORIGINS
          value: '["http://localhost:3000", "http://localhost:5173", "https://84.247.180.172:30772", "http://84.247.180.172:30772", "https://84.247.180.172:30443", "http://84.247.180.172:30443", "https://hermes.duosis.com"]'

        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: hermes
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: core-service
